services:
  web:
    build:
      context: ./apps/resume-ai-web
    depends_on:
      - api

  api:
    build:
      context: ./apps/resume-ai-api
    environment:
      ENVIRONMENT: local
      REDIS_URL: redis://redis:6379/0
      ALLOWED_ORIGINS: "*"
    depends_on:
      - redis
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
      - api
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:v2.55.0
    ports:
      - "9090:9090"
    volumes:
      - ./infra/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api

  grafana:
    image: grafana/grafana:11.3.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./infra/monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infra/monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
